### ISSUE TITLE
API Documentation Broken Link in README

### ISSUE THREAD

**Issue by MarkVLK** [sbehrens/sleepy-puppy#3]
Seems the link to the [API documentation](https://github.com/sbehrens/sleepy-puppy/blob/master/API.md) is broken in your [README](https://github.com/sbehrens/sleepy-puppy/blob/master/README.md).

**Comment by ikkisoft** [comment]
It should be linked to https://github.com/sbehrens/sleepy-puppy/wiki/API

**Comment by sbehrens** [comment]
Thanks for catching that, fixed.
